version = 0.1
[default.deploy.parameters]
stack_name = ""
resolve_s3 = true
s3_prefix = ""
region = "ap-southeast-2"
profile = ""
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
