version = 0.1
[default.deploy.parameters]
stack_name = "jens-file-movestack"
resolve_s3 = true
s3_prefix = "jens_file_move"
region = "ap-southeast-2"
profile = "msa_sandbox"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
