AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'move-s3-object-to-another-bucket'
      PackageType: Image
      ImageUri: 882334376932.dkr.ecr.ap-southeast-2.amazonaws.com/jens-file-moving-app@sha256:a9cdfa8badd08258d45139d8b8bd3a0368948bdfcf687c171b117df8939a3c08
      ImageConfig:
          Command:
          - example_lambda.lambda_handler
      Timeout: 900
      MemorySize: 2008
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Policies:
        - Statement:
          - Effect: Allow
            Action: S3:*
            Resource:
              - arn:aws:s3:::jens-input-bucket
              - arn:aws:s3:::jens-input-bucket/*
              - arn:aws:s3:::jens-output-bucket
              - arn:aws:s3:::jens-output-bucket/*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

  NewLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'unzip-object-save-to-another-bucket'
      PackageType: Image
      ImageUri: 882334376932.dkr.ecr.ap-southeast-2.amazonaws.com/jens-file-moving-app@sha256:a9cdfa8badd08258d45139d8b8bd3a0368948bdfcf687c171b117df8939a3c08
      ImageConfig:
        Command:
          - new_lambda.lambda_handler
      Timeout: 900
      MemorySize: 2008
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Policies:
        - Statement:
            - Effect: Allow
              Action: S3:*
              Resource:
                - arn:aws:s3:::jens-input-bucket
                - arn:aws:s3:::jens-input-bucket/*
                - arn:aws:s3:::jens-output-bucket
                - arn:aws:s3:::jens-output-bucket/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"