FROM amazon/aws-lambda-python:3.12

# Install Python dependencies
COPY app/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt --target "${LAMBDA_TASK_ROOT}"

RUN rm -rf app/
COPY app/ ${LAMBDA_TASK_ROOT}

CMD ["example_lambda.lambda_handler"]